version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres_password
    ports:
      - 5432:5432

  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    ports:
      - 5000:5000

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: "./client"
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 3000:3000

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: "./nginx"
    ports:
      - '3050:80'
